### ISSUE TITLE
#1 Error in Evaluation

### ISSUE THREAD

**Issue by leekichang** [MinkyuKim26/Pytorch_model_template#1]
[model.ipynb.zip](https://github.com/MinkyuKim26/Pytorch_model_template/files/12264847/model.ipynb.zip)

안녕하세요, 개인적으로 MLP Mixer을 구현할 일이 있어 velog 게시물 잘 읽었습니다. 다름이 아니라 제가 구현한 코드에서는 블로그 게시물과 같은 성능이 나오지 않아 세팅 값들이 궁금하여 해당 레포까지 찾아보게 되었습니다. 개인적으로 검토를 해보니 utils.py에서 test loader에서 testset이 아닌 trainset이 들어가고 있어 결과적으로 test accuracy가 아니라 train accuracy가 report되어 있는 것 같습니다. 관련하여서 제가 간단하게 100 epoch 정도 학습/비교를 진행해보니 성능 차이가 꽤나 나는 것 같아 issue 남기고 갑니다.

관련하여서 token mixer와 channel mixer 레이어에서 hidden dimension으로 확장후 다시 원본 차원으로 낮추는 연산이 충분히 구현되지 않아 성능이 잘 나오지 않는 것 같다는 생각이 듭니다.

이미 오래된 게시물과 레포이지만 기회가 되시면 한 번 살펴봐주시면 좋을 것 같습니다.

**Comment by minguinho26** [comment]
안녕하세요, 올려주신 issue 확인하였습니다. 

먼저 업데이트한지 오래된 레포와 블로그 포스트임에도 불구하고 관심 가져주셔서 감사합니다. 

올려주신 내용 확인 후 util.py를 계속 확인하였으나 말씀하신 부분을 확인하지 못하였습니다. 그래서 util.py의  몇 번째 line에서 test loader가 아닌 train loader가 들어갔는지 여쭤보고자 합니다. 

그리고 제가 작성한 모델 코드에서 개선할 수 있는 부분을 가르쳐주셔서 감사합니다. 이 부분 역시 기회가 된다면 말씀하신 방향으로 수정해보도록 하겠습니다. 

다시 한 번 저의 작성 글, 레포에 관심을 가져주셔서 감사합니다.

**Comment by leekichang** [comment]
Line 201 test_dataloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,

이 부분에 오류가 있는게 아닌가 싶습니다.

**Comment by minguinho26** [comment]
안녕하세요, 늦게 답변드려 죄송합니다. 

해당 부분 확인 후 수정하였습니다. 다시 한 번 저의 코드에 피드백을 주셔서 감사합니다.

**Comment by leekichang** [comment]
좋은 자료 공유해주셔서 오히려 감사합니다 :)
